// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactShallowRenderer = require("bs-react-test-renderer/src/ReactShallowRenderer.bs.js");
var Component1$ReactTemplate = require("../src/Component1.bs.js");

describe("Component", (function () {
        return Jest.test("renders", (function () {
                      var component = ReactShallowRenderer.renderWithRenderer(ReasonReact.element(undefined, undefined, Component1$ReactTemplate.make("dogs", /* array */[])));
                      return Jest.ExpectJs[/* toBeDefined */25](Jest.ExpectJs[/* expect */0](component));
                    }));
      }));

/*  Not a pure module */
